@startuml
'https://plantuml.com/use-case-diagram

:Main Admin: as Admin
(Use the application) as (Use)

User -> (Start)
User --> (Use)

Admin ---> (Use)

note right of Admin : This is an example.

note right of (Use)
A note can also
be on several lines
end note

note "This note is connected\nto several objects." as N2
(Start) .. N2
N2 .. (Use)
@enduml

@startuml

actor HR as "HR Advisor"

rectangle Database

rectangle "HR System" {
    usecase UC4 as "4. Get salaries by role"
    usecase UC1 as "1. Produce report on salary of all employees"
    usecase UC2 as "2. Produce report on salary of employees in a department"
    usecase UC3 as "3. Produce report on salary of employees in my department"
    usecase UC5 as "5. Add a new employee's details"
    usecase UC6 as "6. View an employee's details"
    usecase UC7 as "7. Update an employee's details"
    usecase UC8 as "8. Delete an employee's details"

    HR - UC4
    HR - UC1
    HR - UC2
    HR - UC3
    HR - UC5
    HR - UC6
    HR - UC7
    HR - UC8

    UC4 ..> UC1 : include
    UC4 ..> UC2 : include
    UC4 ..> UC3 : include
    UC5 - Database
    UC6 - Database
    UC7 - Database
    UC8 - Database
}

@enduml


