@startuml
'https://plantuml.com/use-case-diagram

:Main Admin: as Admin
(Use the application) as (Use)

User -> (Start)
User --> (Use)

Admin ---> (Use)

note right of Admin : This is an example.

note right of (Use)
A note can also
be on several lines
end note

note "This note is connected\nto several objects." as N2
(Start) .. N2
N2 .. (Use)
@enduml

@startuml

actor HR as "HR Advisor"

rectangle Database

rectangle "HR System" {
    usecase UC4 as "Get salaries
    by role"
    usecase UC1 as "Report employees salaries"

    usecase UCa as "Print salaries"

    HR - UC4
    HR - UC1
    UC4 ..> UCa : include
    'UC4 ..> UC1
}

@enduml

